name: indian_nagish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15

  # Agora SDK
  agora_rtc_engine: ^6.2.4      # Voice/video calls
  
  # Permissions
  permission_handler: ^12.0.1

  socket_io_client: ^2.0.3+1

  # Speech recognition and text-to-speech
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # Backend communication
  http: ^1.0.0

  # Cupertino icons for iOS look
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
